version: '3.7'

services:
    backend:
        stdin_open: true
        build: ./backend
        container_name: backend
        restart: always
        expose:
         - 5000
        ports:
         - 5000:5000
        volumes:
         - ./backend:/usr/src/app 

    frontend:
        stdin_open: true
        build: ./frontend
        expose:
         - 3000
        ports:
         - 3000:3000
        volumes:
         - ./frontend/src:/usr/src/app/src
         - ./frontend/public:/usr/src/app/public
        links:
        - "backend:backend"
        env_file:
        - .env


    nginx:
        image: nginx:1.13 # this will use the latest version of 1.13.x
        ports:
          - '80:80' # expose 80 on host and sent to 80 in container
        depends_on: 
          - frontend
        volumes:
          - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

