version: '3.7'

services:
    backend:
        stdin_open: true
        build: ./backend
        expose:
         - 5000
        ports:
         - 5000:5000
        volumes:
         - ./backend:/usr/src/app

    frontend:
        stdin_open: true
        build: ./frontend
        expose:
         - 3000
        ports:
         - 3000:3000
        volumes:
         - ./frontend/src:/usr/src/app/src
         - ./frontend/public:/usr/src/app/public
        links:
        - "backend:backend"
